#!/bin/sh

TOSH_LCD=/proc/acpi/toshiba/lcd
TOSH_LCD_STORE=/tmp/tshlcd

if [ -e $TOSH_LCD ]; then
	case "$1" in
	 start)
		if [ -e $TOSH_LCD_STORE ]; then
			# restore backlight value
			TOSH_BRIGHTNESS=`cat $TOSH_LCD_STORE`
			sleep 1
			echo 'brightness : '$TOSH_BRIGHTNESS > $TOSH_LCD
			rm $TOSH_LCD_STORE
			TOSH_BRIGHTNESS=$(( `grep brightness: $TOSH_LCD | cut -d: -f2` + 0 ))
			echo $TOSH_BRIGHTNESS >/tmp/afterrestore
		fi
		;;
	 stop)
		# save off backlight value
		TOSH_BRIGHTNESS=$(( `grep brightness: $TOSH_LCD | cut -d: -f2` + 0 ))
		TOSH_MAXBRIGHT=$(( `grep brightness_levels: $TOSH_LCD | cut -d: -f2` - 1))
		# Turn brightness to max to make bios password prompt easier to see
		echo 'brightness : '$TOSH_MAXBRIGHT > $TOSH_LCD
		echo -n $TOSH_BRIGHTNESS > $TOSH_LCD_STORE
		;;
	*)
		echo 'stop to save state, start to restore state'
		;;
	esac
fi



